// File generated by FlutterFire CLI / configuration.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return ios;
      case TargetPlatform.windows:
        return web;
      case TargetPlatform.linux:
        return web;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDzs-qL7Co4knD8FLgNeHfHGn62j0phmUc',
    appId: '1:6990121867:web:6476006e4cffda12407d8e',
    messagingSenderId: '6990121867',
    projectId: 'tugas-akhir-a8ecc',
    authDomain: 'tugas-akhir-a8ecc.firebaseapp.com',
    storageBucket: 'tugas-akhir-a8ecc.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDzs-qL7Co4knD8FLgNeHfHGn62j0phmUc',
    appId: '1:6990121867:android:6476006e4cffda12407d8e',
    messagingSenderId: '6990121867',
    projectId: 'tugas-akhir-a8ecc',
    storageBucket: 'tugas-akhir-a8ecc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDpHBSuW_qR9gZlb0eQ6SMKZFjENqqoOn4',
    appId: '1:6990121867:ios:4dd662bc4a4fb569407d8e',
    messagingSenderId: '6990121867',
    projectId: 'tugas-akhir-a8ecc',
    storageBucket: 'tugas-akhir-a8ecc.firebasestorage.app',
    iosBundleId: 'com.example.tugasAkhir',
  );
}
